export { default as CONTACT } from "./contact";
export { default as EDUCATION } from "./education";
export { default as EXPERIENCE } from "./experience";
export { default as HARD_SKILLS } from "./hardSkills";
export { default as INTERNSHIP } from "./intership";
export { default as LANGUAGES } from "./languages";
export { default as PERSONAL_DETAILS } from "./personalDetails";
export { default as PROFILE } from "./profile";
export { default as VOLUNTEER } from "./volunteer";
